"""Schemas for generated documentation, steps, sections, and export formats."""

from enum import Enum
from typing import List, Optional, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field


class CalloutType(str, Enum):
    """Type of technical manual callout block."""

    NOTE = "note"
    TIP = "tip"
    WARNING = "warning"
    IMPORTANT = "important"


class Callout(BaseModel):
    """Callout block within a documentation step."""

    type: CalloutType
    content: str


class DocumentationStep(BaseModel):
    """A semantic, synthesized step within a procedural guide."""

    step_number: int
    title: str
    instruction: str
    detailed_description: Optional[str] = None
    target_ui_element: Optional[str] = None
    action_type: Optional[str] = None
    input_value_used: Optional[str] = None
    screenshot_url: Optional[str] = None
    screenshot_path: Optional[str] = None
    highlight_selector: Optional[str] = None
    callouts: List[Callout] = Field(default_factory=list)
    raw_action_ids: List[str] = Field(default_factory=list)


class QualityReport(BaseModel):
    """Review report emitted by the Quality Reviewer Agent."""

    score: float = Field(ge=0.0, le=100.0, description="Overall quality score percentage")
    is_approved: bool = True
    completeness_score: float = Field(default=100.0)
    clarity_score: float = Field(default=100.0)
    structure_score: float = Field(default=100.0)
    strengths: List[str] = Field(default_factory=list)
    suggestions: List[str] = Field(default_factory=list)
    missing_items: List[str] = Field(default_factory=list)


class DocumentSchema(BaseModel):
    """Structured documentation generated by the multi-agent pipeline."""

    id: str
    session_id: str
    title: str
    executive_summary: str
    prerequisites: List[str] = Field(default_factory=list)
    steps: List[DocumentationStep] = Field(default_factory=list)
    troubleshooting: List[Dict[str, str]] = Field(default_factory=list)
    raw_markdown: str
    quality_report: Optional[QualityReport] = None
    created_at: datetime
    updated_at: datetime
    version: int = 1


class ExportFormat(str, Enum):
    """Supported export document formats."""

    PDF = "pdf"
    HTML = "html"
    MARKDOWN = "markdown"
    JSON = "json"


class ExportRequest(BaseModel):
    """Request payload to generate an exported document artifact."""

    document_id: str
    format: ExportFormat = ExportFormat.PDF
    theme: str = Field(default="modern", description="Theme: modern, classic, compact")
    include_screenshots: bool = True
    custom_title: Optional[str] = None
